media:
  input: public/images
  output: /images

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/posts
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date

      - name: cover
        label: Cover Image
        type: image

      - name: body
        label: Content
        type: rich-text